Small rework
Tycjan-Fortuna-IT/ProgrammingTechnologies pull request #11
Opened 2023-04-24 18:10 UTC by wuetenderzucker

Small rework of the project in regard to its structure and following adjustments of the code and tests.

2023-04-25 19:23 UTC, Tycjan-Fortuna-IT requested changes
@wuetenderzucker 

One CRITICAL ERROR. The rest is just a suggestion. Doesn't have to be implemented, but consider it. After changes re-request a review.

Also I have made some changes to LogicTests so that we have 100% test coverage, take a look at what was missing (or wrong).

Almost perfect, almost ... 👀

2023-04-25 19:23 UTC, Tycjan-Fortuna-IT commented on Shop/Test/RandomGenerator.cs
> +                dataRepository.AddEvent(null, stateUuid, productUuid, "SupplyEvent", random.Next(5,10));
Why ```productUuid``` is used in the AddEvent method? Shouldn't it be userUuid?
SupplyEvent actually doesn't verify whether this user exists (that's why there is no exception), but other events do.

2023-04-25 19:23 UTC, Tycjan-Fortuna-IT commented on Shop/Test/RandomGenerator.cs
> +                    dataRepository.AddEvent(null, availableGameState.guid, user.guid, "PurchaseEvent");
Here it is correct

2023-04-25 19:23 UTC, Tycjan-Fortuna-IT commented on Shop/Test/RandomGenerator.cs
> +                    dataRepository.AddEvent(null, availableGameState.guid, user.guid, "ReturnEvent");
Here it is correct

2023-04-25 19:23 UTC, Tycjan-Fortuna-IT commented on Shop/Test/RandomGenerator.cs
>                      (state) => (
Maybe add a quick comment about what is actually being checked here?
What means that ```state``` is available?

What ```((Game)state.product).pegi * 365 < age``` means? 
Maybe use properly named ```const``` int? Just a OoL

2023-04-25 19:23 UTC, Tycjan-Fortuna-IT commented on Shop/Test/RandomGenerator.cs
>                  int age = (DateTime.Today - user.dateOfBirth).Days;
As in the next comment, here age is done this ```way```.

2023-04-25 19:23 UTC, Tycjan-Fortuna-IT commented on Shop/Data/Implementation/Game.cs
>          public int pegi { get; set; }
What about creating maybe a ```PegiEnum``` that would contain those allowed PEGI values? What do you think?

2023-04-25 19:23 UTC, Tycjan-Fortuna-IT commented on Shop/Data/Implementation/DataRepository.cs
>          private IDataContext _context;
This ```_context``` looks interesting as suggested by VS. What if we changed it to just ```context```?

2023-05-05 10:37 UTC, wuetenderzucker commented on Shop/Test/RandomGenerator.cs
> +                dataRepository.AddEvent(null, stateUuid, productUuid, "SupplyEvent", random.Next(5,10));
Yes, it should be userUuid indeed, productUuid makes no sense here. I have applied changes and harmonized the names.
Correct.

2023-05-05 11:15 UTC, wuetenderzucker commented on Shop/Test/RandomGenerator.cs
>                      (state) => (
Okay, added a small comment.
Availability requires checking the requirements of the game (i.e., price and PEGI) with corresponding data of the user, their ownership or lack thereof, and quantity in the shop, which is stored in the state. To check all of them it is practical to use `state` of the product as it contains those requirements, directly or indirectly. As a result, the available state here means that the game and its state meet those requirements.

I added a `const int` `DAYS` for the integer.

2023-05-05 11:27 UTC, wuetenderzucker commented on Shop/Data/Implementation/DataRepository.cs
>          private IDataContext _context;
Okay, changed so that the whole program is harmonized.

2023-05-05 11:29 UTC, wuetenderzucker commented on Shop/Data/Implementation/Game.cs
>          public int pegi { get; set; }
Maybe lets not? 😅

2023-05-05 11:59 UTC, Tycjan-Fortuna-IT approved these changes
Nice 🌮 
What took so long? 😄

2023-05-05 11:59 UTC, merged